[package]
name = "dynv6"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
local-ip-address = "0.5"
reqwest = { version = "0.11", default-features = false, features = ["native-tls", "blocking"] }
log = "0.4"
pretty_env_logger = "0.4"
dotenvy = "0.15"
serde = { version = "1.0", features = ["derive"] }
figment = { version = "0.10", features = ["env"] }
once_cell = "1.16.0"

[profile.release]
lto = true
opt-level = 3
strip = true  # Automatically strip symbols from the binary.
codegen-units = 1
panic = "abort"
